timeout: 30
max_retries: 3
retry_delay: 1
headers:
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
  Accept-Encoding: gzip, deflate, br
  Connection: keep-alive 